export enum EmployeesActionTypes {
  SET_EMPLOYEES = 'SET_EMPLOYEES',
  FETCH_EMPLOYEES = 'FETCH_EMPLOYEES',
  FETCH_NEW_EMPLOYEE = 'FETCH_NEW_EMPLOYEE',
  FETCH_UPDATED_EMPLOYEE = 'FETCH_UPDATED_EMPLOYEE',
  UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE = 'DELETE_EMPLOYEE',
  FETCH_DELETED_EMPLOYEE = 'FETCH_DELETED_EMPLOYEE',
  ADD_EMPLOYEE = 'ADD_EMPLOYEE',
  FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START',
  FETCH_EMPLOYEES_END = 'FETCH_EMPLOYEES_END',
  FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR',
}
