export enum EmployeesActionTypes {
    SET_EMPLOYEES = 'SET_EMPLOYEES',
    FETCH_EMPLOYEES = 'FETCH_EMPLOYEES',
    FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START',
    FETCH_EMPLOYEES_END = 'FETCH_EMPLOYEES_END',
    FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR'

}