export enum AuthActionTypes {
    SET_TOKENS = 'SET_TOKENS',
    SET_COOKIES = 'SET_COOKIES',
    FETCH_TOKENS = 'FETCH_TOKENS',
    FETCH_TOKENS_START = 'FETCH_TOKENS_START',
    FETCH_TOKENS_END = 'FETCH_TOKENS_END',
    FETCH_TOKENS_ERROR = 'FETCH_TOKENS_ERROR'
}

//export const FETCH_TOKENS = 'FETCH_TOKENS'