export enum DepartmentsActionTypes {
  SET_DEPARTMENTS = 'SET_DEPARTMENTS',
  FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS',
  SET_DEPARTMENT = 'SET_DEPARTMENT',
  FETCH_DEPARTMENT = 'FETCH_DEPARTMENT',
  FETCH_NEW_DEPARTMENT = 'FETCH_NEW_DEPARTMENT',
  ADD_DEPARTMENT = 'ADD_DEPARTMENT',
  UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',
  FETCH_DEPARTMENTS_START = 'FETCH_DEPARTMENTS_START',
  FETCH_DEPARTMENTS_END = 'FETCH_DEPARTMENTS_END',
  FETCH_DEPARTMENTS_ERROR = 'FETCH_DEPARTMENTS_ERROR',
}
