export enum DepartmentsActionTypes {
  SET_DEPARTMENTS = 'SET_DEPARTMENTS',
  ADD_DEPARTMENT = 'ADD_DEPARTMENT',
  UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',
  FETCH_DEPARTMENTS_START = 'FETCH_DEPARTMENTS_START',
  FETCH_DEPARTMENTS_END = 'FETCH_DEPARTMENTS_END',
  FETCH_DEPARTMENTS_ERROR = 'FETCH_DEPARTMENTS_ERROR',
}
